// NEXUS 3D ARCADE — lightweight WebGL mini-games using Three.js from esm.sh.
(() => {
  const THREE_URL = 'https://esm.sh/three@0.180.0';
  let overlay, mount, renderer, scene, camera, raf = 0, cleanup = () => {};
  let keys = new Set();
  let current = '';

  const games = [
    {id:'runner3d', name:'Neon Runner 3D', emoji:'🏃', desc:'Sprint through a glowing tunnel and dodge barriers.'},
    {id:'space3d', name:'Space Pilot 3D', emoji:'🚀', desc:'Fly through an asteroid field and survive the run.'},
    {id:'maze3d', name:'Cyber Maze 3D', emoji:'🌀', desc:'Navigate a procedural 3D maze to the exit.'},
    {id:'target3d', name:'Target Range 3D', emoji:'🎯', desc:'Click moving targets in a neon arena before time runs out.'},
    {id:'island3d', name:'Voxel Island 3D', emoji:'🏝️', desc:'Explore a tiny procedural 3D voxel-style island.'}
  ];

  const css = `
    .nx3d-overlay{position:fixed;inset:0;z-index:260;background:rgba(1,3,9,.86);backdrop-filter:blur(18px);display:none;align-items:center;justify-content:center;padding:14px}.nx3d-overlay.show{display:flex}
    .nx3d-card{width:min(1260px,98vw);height:min(94vh,940px);overflow:hidden;background:linear-gradient(145deg,#07101a,#101a2b);border:1px solid rgba(255,255,255,.1);border-radius:24px;box-shadow:0 35px 130px #000c;color:#eff5ff;display:flex;flex-direction:column}
    .nx3d-head{display:flex;align-items:center;gap:12px;padding:14px 18px;border-bottom:1px solid rgba(255,255,255,.08);background:rgba(8,13,22,.94)}.nx3d-head b{font:900 16px 'Space Grotesk',sans-serif}.nx3d-head small{display:block;color:#8190a8;font-size:9px;margin-top:2px}.nx3d-spacer{flex:1}
    .nx3d-body{overflow:auto;padding:18px}.nx3d-grid{display:grid;grid-template-columns:repeat(3,minmax(0,1fr));gap:12px}.nx3d-tile{min-height:160px;text-align:left;padding:16px;border:1px solid rgba(255,255,255,.08);border-radius:18px;background:linear-gradient(145deg,#0c1522,#111c2c);color:#eef4ff;cursor:pointer;transition:.18s}.nx3d-tile:hover{transform:translateY(-3px);border-color:rgba(124,108,255,.55);box-shadow:0 18px 50px rgba(70,60,180,.18)}.nx3d-tile .e{font-size:30px;display:block;margin-bottom:10px}.nx3d-tile b{font-size:14px}.nx3d-tile span{display:block;color:#8290a6;font-size:10px;line-height:1.5;margin-top:7px}.nx3d-meta{display:flex;flex-wrap:wrap;gap:7px;margin-bottom:14px}.nx3d-pill{font-size:9px;padding:6px 9px;border-radius:999px;background:#0d1724;border:1px solid rgba(255,255,255,.08);color:#a6b2c5}
    .nx3d-stage{position:relative;height:calc(100% - 0px);min-height:520px;border-radius:18px;overflow:hidden;border:1px solid rgba(255,255,255,.08);background:#030811}.nx3d-stage canvas{width:100%;height:100%;display:block}.nx3d-hud{position:absolute;inset:12px 12px auto 12px;display:flex;align-items:center;gap:8px;pointer-events:none}.nx3d-hud b{padding:8px 10px;background:rgba(6,10,18,.7);border:1px solid rgba(255,255,255,.08);border-radius:10px;font-size:11px}.nx3d-hint{position:absolute;left:14px;bottom:14px;color:#a0abc0;font-size:9px;background:rgba(6,10,18,.72);padding:8px 10px;border-radius:10px;border:1px solid rgba(255,255,255,.07)}
    .nx3d-controls{display:flex;gap:8px;justify-content:center;margin-top:10px;flex-wrap:wrap}.nx3d-btn{border:0;background:#5f51d9;color:#fff;padding:10px 12px;border-radius:10px;font-weight:800;cursor:pointer}.nx3d-btn.ghost{background:#182131;color:#cbd5e5}
    @media(max-width:950px){.nx3d-grid{grid-template-columns:repeat(2,minmax(0,1fr))}}@media(max-width:600px){.nx3d-grid{grid-template-columns:1fr}.nx3d-body{padding:12px}.nx3d-stage{min-height:460px}.nx3d-card{height:96vh}}
  `;

  function styles(){if(document.getElementById('nx3dStyle'))return;const s=document.createElement('style');s.id='nx3dStyle';s.textContent=css;document.head.appendChild(s);}
  function open(){styles();if(!overlay){overlay=document.createElement('div');overlay.id='nx3dOverlay';overlay.className='nx3d-overlay';overlay.innerHTML='<div class="nx3d-card"><div class="nx3d-head"><div><b>NEXUS 3D ARCADE</b><small>WebGL games • keyboard + mouse • no install</small></div><div class="nx3d-spacer"></div><button class="icon-btn" id="nx3dClose">×</button></div><div class="nx3d-body" id="nx3dBody"></div></div>';document.body.appendChild(overlay);document.getElementById('nx3dClose').onclick=home;overlay.onclick=e=>{if(e.target===overlay)home();}}overlay.classList.add('show');}
  function home(){stop();open();const b=document.getElementById('nx3dBody');b.innerHTML='<div class="nx3d-meta"><span class="nx3d-pill">TRUE 3D / WEBGL</span><span class="nx3d-pill">5 GAMES</span><span class="nx3d-pill">NO INSTALL</span><span class="nx3d-pill">THREE.JS</span></div><div class="nx3d-grid">'+games.map(g=>`<button class="nx3d-tile" data-g="${g.id}"><span class="e">${g.emoji}</span><b>${g.name}</b><span>${g.desc}</span><span>3D • PLAY IN BROWSER</span></button>`).join('')+'</div>';b.querySelectorAll('[data-g]').forEach(x=>x.onclick=()=>launch(x.dataset.g));}
  function setupStage(title,hint){stop();open();const b=document.getElementById('nx3dBody');b.innerHTML=`<div class="nx3d-stage" id="nx3dStage"><div class="nx3d-hud"><b id="nx3dScore">${title}</b></div><div class="nx3d-hint">${hint}</div></div><div class="nx3d-controls"><button class="nx3d-btn" id="nx3dRestart">Restart</button><button class="nx3d-btn ghost" id="nx3dBack">3D Arcade</button></div>`;mount=document.getElementById('nx3dStage');document.getElementById('nx3dRestart').onclick=()=>launch(current);document.getElementById('nx3dBack').onclick=home;}
  function bootThree(){return import(THREE_URL);}
  function base(THREE){renderer=new THREE.WebGLRenderer({antialias:true,powerPreference:'high-performance'});renderer.setPixelRatio(Math.min(devicePixelRatio,2));renderer.setSize(mount.clientWidth,mount.clientHeight);renderer.setAnimationLoop(null);mount.appendChild(renderer.domElement);scene=new THREE.Scene();scene.fog=new THREE.Fog(0x050910,35,120);camera=new THREE.PerspectiveCamera(65,mount.clientWidth/mount.clientHeight,.1,300);camera.position.set(0,3,8);scene.add(new THREE.HemisphereLight(0x8fb6ff,0x0b1020,2));const amb=new THREE.AmbientLight(0x4c5a88,.65);scene.add(amb);const resize=()=>{if(!renderer)return;camera.aspect=mount.clientWidth/mount.clientHeight;camera.updateProjectionMatrix();renderer.setSize(mount.clientWidth,mount.clientHeight);};window.addEventListener('resize',resize);const kd=e=>keys.add(e.key.toLowerCase()),ku=e=>keys.delete(e.key.toLowerCase());window.addEventListener('keydown',kd);window.addEventListener('keyup',ku);cleanup=()=>{window.removeEventListener('resize',resize);window.removeEventListener('keydown',kd);window.removeEventListener('keyup',ku);if(renderer){renderer.dispose();renderer.domElement.remove();}renderer=null;scene=null;camera=null;};}
  function loop(fn){const tick=()=>{fn();renderer.render(scene,camera);raf=requestAnimationFrame(tick)};tick();}
  function stop(){cancelAnimationFrame(raf);raf=0;cleanup();keys.clear();}

  async function runner3d(){current='runner3d';setupStage('NEON RUNNER 3D','A/D or ←/→ to switch lanes • dodge barriers');const THREE=await bootThree();if(current!=='runner3d')return;base(THREE);const road=new THREE.Mesh(new THREE.BoxGeometry(16,.2,180),new THREE.MeshStandardMaterial({color:0x08111e,metalness:.25,roughness:.55}));road.position.z=-75;scene.add(road);for(let i=-6;i<=6;i+=3){const lane=new THREE.Mesh(new THREE.BoxGeometry(.06,.03,180),new THREE.MeshBasicMaterial({color:0x384b70}));lane.position.x=i;lane.position.y=.12;lane.position.z=-75;scene.add(lane);}const player=new THREE.Mesh(new THREE.BoxGeometry(1.3,.7,2.1),new THREE.MeshStandardMaterial({color:0x6f5cff,emissive:0x3020a0,emissiveIntensity:1.2}));player.position.y=.7;player.position.z=3;scene.add(player);const obstacles=[];let lane=0,score=0,t=0,dead=false;camera.position.set(0,4.2,9);camera.lookAt(0,1,-25);for(let i=0;i<40;i++){const o=new THREE.Mesh(new THREE.BoxGeometry(1.6,1.2,2.4),new THREE.MeshStandardMaterial({color:0xff4d7b,emissive:0x5a1230,emissiveIntensity:1}));o.position.set([-6,-3,0,3,6][Math.floor(Math.random()*5)],.7,-10-i*9-Math.random()*5);scene.add(o);obstacles.push(o);}loop(()=>{if(dead){document.getElementById('nx3dScore').textContent=`CRASH • SCORE ${score}`;return;}t++;if(keys.has('a')||keys.has('arrowleft')){lane=Math.max(-2,lane-1);keys.delete('a');keys.delete('arrowleft');}if(keys.has('d')||keys.has('arrowright')){lane=Math.min(2,lane+1);keys.delete('d');keys.delete('arrowright');}player.position.x+=((lane*3)-player.position.x)*.15;obstacles.forEach(o=>{o.position.z+=.24+score*.001;if(o.position.z>8){o.position.z=-370-Math.random()*60;o.position.x=[-6,-3,0,3,6][Math.floor(Math.random()*5)];score++;}});if(obstacles.some(o=>Math.abs(o.position.x-player.position.x)<1.25&&Math.abs(o.position.z-player.position.z)<1.8)){dead=true;}document.getElementById('nx3dScore').textContent=dead?`CRASH • SCORE ${score}`:`DISTANCE ${score}`;});}

  async function space3d(){current='space3d';setupStage('SPACE PILOT 3D','WASD / arrows to fly • avoid asteroids');const THREE=await bootThree();if(current!=='space3d')return;base(THREE);scene.background=new THREE.Color(0x02040c);camera.position.set(0,1,10);camera.lookAt(0,0,-25);const ship=new THREE.Mesh(new THREE.ConeGeometry(.8,2.6,8),new THREE.MeshStandardMaterial({color:0x79e6ff,emissive:0x12445c,emissiveIntensity:1.2}));ship.rotation.x=Math.PI/2;scene.add(ship);const stars=new THREE.Points(new THREE.BufferGeometry(),new THREE.PointsMaterial({color:0x9ec9ff,size:.12}));const arr=[];for(let i=0;i<800;i++)arr.push((Math.random()-.5)*140,(Math.random()-.5)*90,-Math.random()*250);stars.geometry.setAttribute('position',new THREE.Float32BufferAttribute(arr,3));scene.add(stars);const ast=[];for(let i=0;i<60;i++){const a=new THREE.Mesh(new THREE.IcosahedronGeometry(.6+Math.random()*1.5,1),new THREE.MeshStandardMaterial({color:0x887f9b,roughness:1}));a.position.set((Math.random()-.5)*35,(Math.random()-.5)*24,-30-Math.random()*220);scene.add(a);ast.push(a);}let score=0,dead=false;loop(()=>{if(dead){document.getElementById('nx3dScore').textContent=`MISSION END • ${score}`;return;}const sp=.38;ship.position.x+=((keys.has('a')||keys.has('arrowleft')?-sp:0)+(keys.has('d')||keys.has('arrowright')?sp:0));ship.position.y+=((keys.has('w')||keys.has('arrowup')?sp:0)+(keys.has('s')||keys.has('arrowdown')?-sp:0));ship.position.x=Math.max(-11,Math.min(11,ship.position.x));ship.position.y=Math.max(-7,Math.min(7,ship.position.y));ast.forEach(a=>{a.position.z+=.5;a.rotation.x+=.01;a.rotation.y+=.015;if(a.position.z>12){a.position.z=-220; a.position.x=(Math.random()-.5)*35;a.position.y=(Math.random()-.5)*24;score++;}});if(ast.some(a=>a.position.z>2&&a.position.z<7&&a.position.distanceTo(ship.position)<1.7))dead=true;document.getElementById('nx3dScore').textContent=`SCORE ${score}`;});}

  async function maze3d(){current='maze3d';setupStage('CYBER MAZE 3D','WASD / arrows • find the cyan exit');const THREE=await bootThree();if(current!=='maze3d')return;base(THREE);camera.position.set(0,9,14);camera.rotation.x=-.65;const group=new THREE.Group();scene.add(group);const size=9,cell=4;const wallMat=new THREE.MeshStandardMaterial({color:0x273a57,metalness:.5,roughness:.4,emissive:0x081020});for(let z=0;z<size;z++)for(let x=0;x<size;x++){if((x===0&&z===0)||(x===size-1&&z===size-1))continue;if((Math.random()>.52&&x%2===0)||(Math.random()>.58&&z%2===1)){const w=new THREE.Mesh(new THREE.BoxGeometry(cell,.9,cell*.9),wallMat);w.position.set((x-size/2)*cell,.45,(z-size/2)*cell);group.add(w);}}const floor=new THREE.Mesh(new THREE.BoxGeometry(size*cell,.15,size*cell),new THREE.MeshStandardMaterial({color:0x08111b}));floor.position.y=-.1;scene.add(floor);const p=new THREE.Mesh(new THREE.SphereGeometry(.65,18,18),new THREE.MeshStandardMaterial({color:0xa58cff,emissive:0x4c2dc5,emissiveIntensity:1.4}));p.position.set((-size/2)*cell,0.7,(-size/2)*cell);scene.add(p);const goal=new THREE.Mesh(new THREE.BoxGeometry(2,1.2,2),new THREE.MeshStandardMaterial({color:0x6fffe0,emissive:0x1c806f,emissiveIntensity:2}));goal.position.set((size/2)*cell-cell,0.6,(size/2)*cell-cell);scene.add(goal);let score=0;loop(()=>{const sp=.18;p.position.x+=((keys.has('d')||keys.has('arrowright')?sp:0)-(keys.has('a')||keys.has('arrowleft')?sp:0));p.position.z+=((keys.has('s')||keys.has('arrowdown')?sp:0)-(keys.has('w')||keys.has('arrowup')?sp:0));p.position.x=Math.max(-16,Math.min(16,p.position.x));p.position.z=Math.max(-16,Math.min(16,p.position.z));camera.position.x=p.position.x*.45;camera.position.z=p.position.z+13;camera.lookAt(p.position.x,0,p.position.z-10);if(p.position.distanceTo(goal.position)<2.1){score++;p.position.set(-18,0.7,-18);}document.getElementById('nx3dScore').textContent=`EXITS ${score}`;});}

  async function target3d(){current='target3d';setupStage('TARGET RANGE 3D','Move mouse and click targets • 30 seconds');const THREE=await bootThree();if(current!=='target3d')return;base(THREE);camera.position.set(0,3,16);camera.lookAt(0,1,-12);const floor=new THREE.Mesh(new THREE.BoxGeometry(34,.2,34),new THREE.MeshStandardMaterial({color:0x07111c}));floor.position.y=-.1;scene.add(floor);const targets=[];const ray=new THREE.Raycaster();const pointer=new THREE.Vector2();for(let i=0;i<12;i++){const t=new THREE.Mesh(new THREE.SphereGeometry(.65,18,18),new THREE.MeshStandardMaterial({color:0xff5d9a,emissive:0x65102f,emissiveIntensity:1.2}));t.position.set((Math.random()-.5)*26,1+Math.random()*7,-8-Math.random()*20);scene.add(t);targets.push(t);}let score=0,start=performance.now();const move=e=>{const r=renderer.domElement.getBoundingClientRect();pointer.x=((e.clientX-r.left)/r.width)*2-1;pointer.y=-((e.clientY-r.top)/r.height)*2+1;};const click=()=>{ray.setFromCamera(pointer,camera);const hit=ray.intersectObjects(targets)[0];if(hit){hit.object.position.set((Math.random()-.5)*26,1+Math.random()*7,-8-Math.random()*20);score++;}};renderer.domElement.addEventListener('pointermove',move);renderer.domElement.addEventListener('pointerdown',click);cleanup=()=>{renderer.domElement.removeEventListener('pointermove',move);renderer.domElement.removeEventListener('pointerdown',click);};loop(()=>{const left=Math.max(0,30-(performance.now()-start)/1000);targets.forEach((t,i)=>t.position.y+=Math.sin(performance.now()/300+i)*.002);document.getElementById('nx3dScore').textContent=`HITS ${score} • ${left.toFixed(1)}s`;if(left<=0)cancelAnimationFrame(raf);});}

  async function island3d(){current='island3d';setupStage('VOXEL ISLAND 3D','WASD / arrows • explore the island');const THREE=await bootThree();if(current!=='island3d')return;base(THREE);camera.position.set(0,12,18);const world=new THREE.Group();scene.add(world);const mat=[0x2a8b7b,0x6eaf58,0x4f8e4c,0x74665b].map(c=>new THREE.MeshStandardMaterial({color:c,roughness:1}));for(let x=-12;x<=12;x++)for(let z=-12;z<=12;z++){const h=Math.max(0,4-Math.hypot(x,z)/4+Math.sin(x*.8)*.7+Math.cos(z*.6)*.5);for(let y=0;y<Math.max(1,Math.floor(h));y++){const m=new THREE.Mesh(new THREE.BoxGeometry(1,1,1),mat[y===0?3:(y<2?0:1)]);m.position.set(x,y,z);world.add(m);}}const avatar=new THREE.Mesh(new THREE.BoxGeometry(.7,1.2,.7),new THREE.MeshStandardMaterial({color:0xa58cff,emissive:0x4b2fb0,emissiveIntensity:1}));avatar.position.y=2;world.add(avatar);let steps=0;loop(()=>{const sp=.12;avatar.position.x+=(keys.has('d')||keys.has('arrowright')?sp:0)-(keys.has('a')||keys.has('arrowleft')?sp:0);avatar.position.z+=(keys.has('s')||keys.has('arrowdown')?sp:0)-(keys.has('w')||keys.has('arrowup')?sp:0);avatar.position.x=Math.max(-12,Math.min(12,avatar.position.x));avatar.position.z=Math.max(-12,Math.min(12,avatar.position.z));camera.position.x=avatar.position.x*.7;camera.position.z=avatar.position.z+16;camera.lookAt(avatar.position.x,1,avatar.position.z);steps++;document.getElementById('nx3dScore').textContent=`EXPLORE • ${Math.floor(steps/10)}M` ;});}

  async function launch(id){current=id;if(id==='runner3d')return runner3d();if(id==='space3d')return space3d();if(id==='maze3d')return maze3d();if(id==='target3d')return target3d();if(id==='island3d')return island3d();home();}

  function init(){const nav=document.querySelector('.nav-group');if(nav&&!document.getElementById('3dGamesBtn')){const b=document.createElement('button');b.className='nav-item';b.id='3dGamesBtn';b.innerHTML='🧊 <span>3D Arcade</span>';b.onclick=home;nav.appendChild(b);}}
  init();
  window.NEXUS_3D={open:home};
})();
