// NEXUS message actions — persistent saves, pins, reactions and copy actions.
import { createClient } from 'https://esm.sh/@supabase/supabase-js@2';
const cfg=window.NEXUS_SUPABASE||{};
const sb=cfg.url&&cfg.publishableKey?createClient(cfg.url,cfg.publishableKey):null;
const $=s=>document.querySelector(s);
const toast=t=>{const e=$('#toast');if(!e)return;e.textContent=t;e.classList.add('show');clearTimeout(window.__nxActToast);window.__nxActToast=setTimeout(()=>e.classList.remove('show'),2300)};
const getSession=async()=>{if(window.NEXUS_SESSION)return window.NEXUS_SESSION;if(!sb)return null;const {data}=await sb.auth.getSession();return data.session};
async function saveMessage(id){const s=await getSession();if(!s||!sb)return toast('Sign in to save messages');const {error}=await sb.from('saved_messages').upsert({user_id:s.user.id,message_id:id},{onConflict:'user_id,message_id'});toast(error?error.message:'Saved to your vault');}
async function pinMessage(id){const s=await getSession();if(!s||!sb)return toast('Sign in to pin messages');const {error}=await sb.from('pinned_messages').upsert({message_id:id,pinned_by:s.user.id},{onConflict:'message_id'});toast(error?error.message:'Message pinned');}
async function react(id,emoji){const s=await getSession();if(!s||!sb)return toast('Sign in to react');const {error}=await sb.from('message_reactions').upsert({message_id:id,user_id:s.user.id,emoji});toast(error?error.message:`${emoji} reaction saved`);}
async function copyMessage(id){const el=document.querySelector(`[data-message-id="${CSS.escape(id)}"] p`);if(!el)return;try{await navigator.clipboard.writeText(el.innerText);toast('Message copied');}catch{toast('Clipboard permission blocked');}}
function wire(){document.addEventListener('click',e=>{const msg=e.target.closest?.('.message');if(!msg)return;const id=msg.dataset.messageId;if(!id)return;const save=e.target.closest?.('[data-save]');const more=e.target.closest?.('[data-more]');const reaction=e.target.closest?.('.reaction-row button');if(save){e.preventDefault();e.stopImmediatePropagation();saveMessage(id);return;}if(more){e.preventDefault();e.stopImmediatePropagation();const menu=document.createElement('div');menu.style.cssText='position:fixed;z-index:200;padding:6px;border:1px solid var(--line);border-radius:12px;background:#0c1119;box-shadow:0 20px 70px #000b;display:grid;gap:4px';menu.innerHTML='<button data-a="copy">Copy message</button><button data-a="save">Save message</button><button data-a="pin">Pin message</button>';document.body.appendChild(menu);const r=msg.getBoundingClientRect();menu.style.left=Math.min(innerWidth-170,r.right-170)+'px';menu.style.top=Math.min(innerHeight-140,r.bottom+6)+'px';menu.querySelectorAll('button').forEach(b=>{b.style.cssText='border:0;background:#151c29;color:#d8e0ee;padding:8px 10px;border-radius:8px;text-align:left;cursor:pointer';b.onclick=()=>{const a=b.dataset.a;menu.remove();if(a==='copy')copyMessage(id);if(a==='save')saveMessage(id);if(a==='pin')pinMessage(id)}});setTimeout(()=>{const close=ev=>{if(!menu.contains(ev.target)){menu.remove();document.removeEventListener('click',close)}};document.addEventListener('click',close)},0);return;}if(reaction&&reaction.textContent.trim()&&!reaction.classList.contains('add-reaction')){e.preventDefault();e.stopImmediatePropagation();const emoji=reaction.textContent.replace(/\s*\d+$/,'').trim();if(emoji)react(id,emoji);}} ,true);}
wire();
window.NEXUS_ACTIONS={saveMessage,pinMessage,react,copyMessage};
