// NEXUS ARCADE — extra original mini-games + curated open-source web arcade links.
const Arcade = (() => {
  const $ = (s) => document.querySelector(s);
  let overlay, canvas, ctx, frame = 0, raf = 0, cleanup = () => {};
  let score = 0, bestKey = 'nexus:arcade:best:';

  const local = (key, val) => {
    if (val === undefined) return Number(localStorage.getItem(bestKey + key) || 0);
    const old = local(key); const n = Math.max(old, Math.floor(val));
    localStorage.setItem(bestKey + key, String(n)); return n;
  };

  const games = [
    ['snake','Snake Matrix','🐍','Grow, dodge, survive.','Solo'],
    ['pong','Neon Pong','🏓','Beat the adaptive AI.','Solo'],
    ['breakout','Breakout','🧱','Smash the neon wall.','Solo'],
    ['dodge','Star Dodge','☄️','Survive the falling storm.','Solo'],
    ['miner','Space Miner','💎','Collect crystals, avoid drones.','Solo'],
    ['tap','Tap Frenzy','⚡','30 seconds. Maximum taps.','Solo'],
    ['aim','Aim Rush','🎯','Hit moving targets fast.','Solo'],
    ['color','Color Switch','🌈','Pick the word, not the ink.','Solo'],
    ['math','Math Sprint','➗','Solve before the timer ends.','Solo'],
    ['lights','Memory Lights','💡','Repeat the sequence.','Solo'],
    ['tiles','Tile Rush','🔢','Merge tiles and chase 2048-style scores.','Solo'],
    ['maze','Maze Escape','🌀','Find the exit as fast as possible.','Solo'],
    ['rhythm','Beat Tap','🎵','Hit the pulse at the right moment.','Solo'],
    ['orbit','Orbit Dodger','🪐','Rotate around the core and stay alive.','Solo'],
    ['scramble','Word Scramble','🔤','Unscramble as many words as you can.','Solo'],
    ['clicker','Cosmic Clicker','🚀','Build a ridiculous score streak.','Solo'],
    ['webmaze','Web Arcade: Maze','🌐','Open-source browser game from the web.','Web'],
    ['libre','Libre Arcade','🕹️','Open-source collection: Snake, Breakout, Space Invaders and more.','Web']
  ];

  const words = ['NEXUS','GALAXY','ROVER','CODING','ROBOT','MATRIX','QUANTUM','PIXEL','CYBER','ROCKET','ORBIT','COMET','LASER','SERVER','PLASMA'];
  const rand = (a,b) => Math.random()*(b-a)+a;
  const int = (a,b) => Math.floor(rand(a,b+1));
  const esc = s => String(s).replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));

  function styles(){
    if ($('#nxArcadeStyle')) return;
    const s=document.createElement('style'); s.id='nxArcadeStyle'; s.textContent=`
      .nxa-overlay{position:fixed;inset:0;z-index:240;background:rgba(2,4,10,.82);backdrop-filter:blur(20px);display:none;align-items:center;justify-content:center;padding:16px}.nxa-overlay.show{display:flex}.nxa-card{width:min(1180px,97vw);height:min(92vh,900px);overflow:hidden;background:linear-gradient(145deg,#09101b,#111a2a);border:1px solid rgba(255,255,255,.1);border-radius:24px;box-shadow:0 40px 140px #000e;color:#eff5ff;display:flex;flex-direction:column}.nxa-head{display:flex;align-items:center;gap:12px;padding:14px 18px;border-bottom:1px solid rgba(255,255,255,.08);background:rgba(8,13,22,.94);backdrop-filter:blur(14px)}.nxa-head b{font:900 16px 'Space Grotesk',sans-serif}.nxa-head small{display:block;color:#7e8ca4;font-size:9px;margin-top:2px}.nxa-spacer{flex:1}.nxa-body{overflow:auto;padding:18px}.nxa-grid{display:grid;grid-template-columns:repeat(4,minmax(0,1fr));gap:10px}.nxa-tile{min-height:126px;text-align:left;padding:14px;border-radius:16px;border:1px solid rgba(255,255,255,.08);background:linear-gradient(145deg,#0c1522,#111c2c);color:#eef4ff;cursor:pointer;transition:.18s}.nxa-tile:hover{transform:translateY(-3px) scale(1.01);border-color:rgba(124,108,255,.55);box-shadow:0 18px 44px rgba(70,60,180,.16)}.nxa-tile .e{font-size:26px;display:block;margin-bottom:7px}.nxa-tile b{font-size:13px}.nxa-tile span{display:block;color:#7f8da6;font-size:9px;line-height:1.45;margin-top:6px}.nxa-tags{display:flex;flex-wrap:wrap;gap:7px;margin-bottom:14px}.nxa-tag{font-size:9px;padding:6px 9px;border-radius:999px;background:#0e1725;border:1px solid rgba(255,255,255,.08);color:#a6b2c5}.nxa-toolbar{display:flex;gap:8px;margin-bottom:12px;align-items:center}.nxa-search{flex:1;background:#080e17;border:1px solid rgba(255,255,255,.08);border-radius:10px;color:#fff;padding:10px}.nxa-btn{border:0;background:#5f51d9;color:#fff;padding:10px 12px;border-radius:10px;font-weight:800;cursor:pointer}.nxa-btn.ghost{background:#182131;color:#cdd7e7}.nxa-board{display:flex;flex-direction:column;align-items:center;gap:10px}.nxa-stat{font-size:11px;color:#9ca9bd;text-align:center}.nxa-canvas{width:min(760px,100%);aspect-ratio:16/10;background:#050b12;border:1px solid rgba(255,255,255,.08);border-radius:18px;display:block;touch-action:none}.nxa-controls{display:flex;gap:8px;flex-wrap:wrap;justify-content:center}.nxa-web{display:grid;grid-template-columns:1fr 1fr;gap:12px}.nxa-webcard{border:1px solid rgba(255,255,255,.08);border-radius:16px;background:#0d1623;padding:16px}.nxa-webcard h3{margin:0 0 6px;font-size:13px}.nxa-webcard p{color:#8491a7;font-size:10px;line-height:1.55}.nxa-webcard button{margin-top:8px}.nxa-help{font-size:9px;color:#7f8ca1;text-align:center}.nxa-overlay .icon-btn{background:#151e2d}
      @media(max-width:900px){.nxa-grid{grid-template-columns:repeat(2,minmax(0,1fr))}.nxa-web{grid-template-columns:1fr}}@media(max-width:600px){.nxa-grid{grid-template-columns:1fr 1fr}.nxa-body{padding:12px}.nxa-card{height:95vh}.nxa-toolbar{flex-wrap:wrap}.nxa-search{flex-basis:100%}}
    `; document.head.appendChild(s);
  }

  function open(){
    styles();
    if(!overlay){
      overlay=document.createElement('div'); overlay.id='nxaOverlay'; overlay.className='nxa-overlay';
      overlay.innerHTML=`<div class="nxa-card"><div class="nxa-head"><div><b>NEXUS ARCADE</b><small>Quick games • challenge yourself • discover web games</small></div><div class="nxa-spacer"></div><button class="icon-btn" id="nxaClose">×</button></div><div class="nxa-body" id="nxaBody"></div></div>`;
      document.body.appendChild(overlay);
      $('#nxaClose').onclick=home; overlay.addEventListener('click',e=>{if(e.target===overlay)home();});
    }
    overlay.classList.add('show');
  }

  function home(){cleanup();cancelAnimationFrame(raf);if(overlay)overlay.classList.remove('show');renderHome();}
  function renderHome(){
    open();
    const b=$('#nxaBody');
    b.innerHTML=`<div class="nxa-tags"><span class="nxa-tag">${games.length} ARCADE PICKS</span><span class="nxa-tag">SOLO CHALLENGES</span><span class="nxa-tag">NO INSTALL</span><span class="nxa-tag">WEB ARCADE</span></div><div class="nxa-toolbar"><input class="nxa-search" id="nxaSearch" placeholder="Search games…"><button class="nxa-btn" id="nxaRandom">🎲 Random</button></div><div class="nxa-grid" id="nxaGrid"></div>`;
    const render=()=>{const q=($('#nxaSearch').value||'').toLowerCase();$('#nxaGrid').innerHTML=games.filter(g=>g[1].toLowerCase().includes(q)||g[2].includes(q)||g[3].toLowerCase().includes(q)).map(g=>`<button class="nxa-tile" data-game="${g[0]}"><span class="e">${g[2]}</span><b>${esc(g[1])}</b><span>${esc(g[3])}</span><span>${g[4]}</span></button>`).join(''); $('#nxaGrid').querySelectorAll('[data-game]').forEach(x=>x.onclick=()=>launch(x.dataset.game));};
    $('#nxaSearch').oninput=render; $('#nxaRandom').onclick=()=>launch(games[int(0,games.length-1)][0]); render();
  }

  function shell(title,help=''){
    const b=$('#nxaBody'); score=0; b.innerHTML=`<div class="nxa-board"><div class="nxa-stat" id="nxaStat">${esc(title)}</div><canvas class="nxa-canvas" id="nxaCanvas" width="960" height="600"></canvas><div class="nxa-controls"><button class="nxa-btn" id="nxaRestart">Restart</button><button class="nxa-btn ghost" id="nxaBack">Arcade</button></div><div class="nxa-help">${esc(help)}</div></div>`;
    canvas=$('#nxaCanvas');ctx=canvas.getContext('2d');$('#nxaRestart').onclick=()=>launch(currentGame);$('#nxaBack').onclick=home;
  }
  let currentGame='';
  function launch(id){
    cleanup();cancelAnimationFrame(raf);currentGame=id;
    if(id==='webmaze'){ openWeb('https://duysqubix.github.io/web-arcade/','Web Arcade — open-source browser games'); return; }
    if(id==='libre'){ openWeb('https://github.com/linkingtechnologies/libre-arcade','Libre Arcade — open-source game collection'); return; }
    open();
    ({snake:snake,pong:pong,breakout:breakout,dodge:dodge,miner:miner,tap:tap,aim:aim,color:color,math:math,lights:lights,tiles:tiles,maze:maze,rhythm:rhythm,orbit:orbit,scramble:scramble,clicker:clicker}[id]||home)();
  }
  function ui(t){$('#nxaStat').textContent=t;}
  function fill(c='#050b12'){ctx.fillStyle=c;ctx.fillRect(0,0,canvas.width,canvas.height);}
  function line(x1,y1,x2,y2){ctx.beginPath();ctx.moveTo(x1,y1);ctx.lineTo(x2,y2);ctx.stroke();}
  function keySet(){const k=new Set();const kd=e=>k.add(e.key.toLowerCase());const ku=e=>k.delete(e.key.toLowerCase());window.addEventListener('keydown',kd);window.addEventListener('keyup',ku);cleanup=()=>{window.removeEventListener('keydown',kd);window.removeEventListener('keyup',ku);};return k;}

  function snake(){shell('Snake Matrix','Arrow keys / WASD. Eat nodes, grow longer, never hit the wall or yourself.');const k=keySet();let grid=24,s=canvas.width/grid,body=[[12,12],[11,12],[10,12]],dir=[1,0],next=[1,0],food=[int(2,21),int(2,21)],tick=0,dead=false;
    const place=()=>{do{food=[int(1,22),int(1,22)]}while(body.some(p=>p[0]===food[0]&&p[1]===food[1]))}; place();
    const loop=()=>{if(dead){draw();return;}if((k.has('arrowup')||k.has('w'))&&dir[1]!==1)next=[0,-1];if((k.has('arrowdown')||k.has('s'))&&dir[1]!==-1)next=[0,1];if((k.has('arrowleft')||k.has('a'))&&dir[0]!==1)next=[-1,0];if((k.has('arrowright')||k.has('d'))&&dir[0]!==-1)next=[1,0];tick++;if(tick%6===0){dir=next;const h=[body[0][0]+dir[0],body[0][1]+dir[1]];if(h[0]<0||h[0]>=grid||h[1]<0||h[1]>=grid||body.some(p=>p[0]===h[0]&&p[1]===h[1])){dead=true;local('snake',score);ui(`GAME OVER • ${score} • BEST ${local('snake')}`);}else{body.unshift(h);if(h[0]===food[0]&&h[1]===food[1]){score++;place();}else body.pop();}}draw();raf=requestAnimationFrame(loop)};
    const draw=()=>{fill();for(let i=0;i<grid;i++){for(let j=0;j<grid;j++){ctx.fillStyle=(i+j)%2?'#0a111b':'#08101a';ctx.fillRect(i*s,j*s,s-1,s-1)}}ctx.fillStyle='#7cf58a';ctx.fillRect(food[0]*s+4,food[1]*s+4,s-8,s-8);body.forEach((p,i)=>{ctx.fillStyle=i?'#6e64ff':'#b9b4ff';ctx.fillRect(p[0]*s+3,p[1]*s+3,s-6,s-6)});ui(dead?`GAME OVER • SCORE ${score} • BEST ${local('snake')}`:`SCORE ${score} • BEST ${local('snake')}`);};loop();}

  function pong(){shell('Neon Pong','W/S or Arrow keys. Beat the adaptive CPU. First to 7.');const k=keySet();let py=250,ay=250,bx=480,by=300,vx=5,vy=3,meS=0,aiS=0,over=false;const reset=(who)=>{bx=480;by=int(80,520);vx=who==='me'?5:-5;vy=rand(-4,4)||2};
    const loop=()=>{py+=(k.has('w')||k.has('arrowup')?-6:0)+(k.has('s')||k.has('arrowdown')?6:0);py=Math.max(20,Math.min(480,py));ay+=(by>ay+50?4:-4);ay=Math.max(20,Math.min(480,ay));bx+=vx;by+=vy;if(by<12||by>588)vy*=-1;if(bx<32&&by>py&&by<py+100){vx=Math.abs(vx)*1.04;vy+=(by-(py+50))/30;}if(bx>928&&by>ay&&by<ay+100){vx=-Math.abs(vx)*1.04;vy+=(by-(ay+50))/30;}if(bx<0){aiS++;reset('ai')}if(bx>960){meS++;reset('me')}if(meS>=7||aiS>=7){over=true;local('pong',meS*10-aiS);ui(`MATCH ${meS>aiS?'WON':'LOST'} • ${meS}-${aiS} • BEST ${local('pong')}`);}draw();if(!over)raf=requestAnimationFrame(loop)};const draw=()=>{fill();ctx.strokeStyle='#2b3a50';ctx.setLineDash([8,12]);line(480,0,480,600);ctx.setLineDash([]);ctx.fillStyle='#ffffff';ctx.fillRect(18,py,12,100);ctx.fillRect(930,ay,12,100);ctx.beginPath();ctx.arc(bx,by,10,0,7);ctx.fill();ctx.font='700 54px Space Grotesk, sans-serif';ctx.fillText(meS,420,65);ctx.fillText(aiS,520,65);ui(over?`FINAL ${meS} – ${aiS}`:`YOU ${meS} • CPU ${aiS}`)};loop();}

  function breakout(){shell('Breakout','Move with mouse or Arrow keys. Clear every block.');const k=keySet();let px=420,bx=480,by=520,vx=4,vy=-4,blocks=[];for(let r=0;r<5;r++)for(let c=0;c<10;c++)blocks.push({x:90+c*78,y:70+r*30,on:1});let over=0;
    const loop=()=>{px+=(k.has('arrowleft')||k.has('a')?-7:0)+(k.has('arrowright')||k.has('d')?7:0);px=Math.max(20,Math.min(820,px));bx+=vx;by+=vy;if(bx<10||bx>950)vx*=-1;if(by<10)vy*=-1;if(by>560&&bx>px&&bx<px+120)vy=-Math.abs(vy);for(const q of blocks)if(q.on&&bx>q.x&&bx<q.x+64&&by>q.y&&by<q.y+18){q.on=0;vy*=-1;score++;break;}if(by>620)over=1;if(blocks.every(q=>!q.on))over=2;draw();if(!over)raf=requestAnimationFrame(loop);else{local('breakout',score);ui(over===2?`CLEARED! SCORE ${score} • BEST ${local('breakout')}`:`MISS • SCORE ${score} • BEST ${local('breakout')}`)}};const draw=()=>{fill();blocks.forEach((q,i)=>{if(q.on){ctx.fillStyle=`hsl(${i*9},75%,62%)`;ctx.fillRect(q.x,q.y,64,18)}});ctx.fillStyle='#bdb6ff';ctx.fillRect(px,570,120,14);ctx.fillStyle='#fff';ctx.beginPath();ctx.arc(bx,by,8,0,7);ctx.fill();ui(`SCORE ${score} • BLOCKS ${blocks.filter(x=>x.on).length}`)};canvas.addEventListener('mousemove',e=>{const r=canvas.getBoundingClientRect();px=((e.clientX-r.left)/r.width*canvas.width)-60});loop();}

  function dodge(){shell('Star Dodge','Arrow keys / WASD. Survive 40 seconds; the storm gets faster.');const k=keySet();let x=480,y=520,obs=[],t=0,dead=0;for(let i=0;i<18;i++)obs.push({x:rand(20,940),y:rand(-700,0),s:rand(2,5),r:rand(7,16)});const loop=()=>{x+=(k.has('a')||k.has('arrowleft')?-5:0)+(k.has('d')||k.has('arrowright')?5:0);y+=(k.has('w')||k.has('arrowup')?-5:0)+(k.has('s')||k.has('arrowdown')?5:0);x=Math.max(18,Math.min(942,x));y=Math.max(18,Math.min(582,y));t++;obs.forEach(o=>{o.y+=o.s+(t/2000);if(o.y>620){o.y=-20;o.x=rand(10,950);score++}if(Math.hypot(o.x-x,o.y-y)<o.r+14)dead=1});draw();if(t<2400&&!dead)raf=requestAnimationFrame(loop);else{local('dodge',score);ui(dead?`CRASH • SCORE ${score} • BEST ${local('dodge')}`:`SURVIVED • SCORE ${score} • BEST ${local('dodge')}`)}};const draw=()=>{fill();ctx.fillStyle='#ffffff';obs.forEach(o=>{ctx.beginPath();ctx.arc(o.x,o.y,o.r,0,7);ctx.fill()});ctx.fillStyle='#7b6cff';ctx.beginPath();ctx.moveTo(x,y-18);ctx.lineTo(x-14,y+12);ctx.lineTo(x+14,y+12);ctx.closePath();ctx.fill();ui(`SURVIVAL ${(t/60).toFixed(1)}s • SCORE ${score}`)};loop();}

  function miner(){shell('Space Miner','Arrow keys / WASD. Collect blue crystals. Avoid drone zones.');const k=keySet();let x=480,y=520,cr=[],dr=[];for(let i=0;i<12;i++)cr.push({x:rand(30,930),y:rand(30,560)});for(let i=0;i<5;i++)dr.push({x:rand(30,930),y:rand(30,560),vx:rand(-2,2),vy:rand(-2,2)});let hit=0;const loop=()=>{x+=(k.has('a')||k.has('arrowleft')?-5:0)+(k.has('d')||k.has('arrowright')?5:0);y+=(k.has('w')||k.has('arrowup')?-5:0)+(k.has('s')||k.has('arrowdown')?5:0);x=Math.max(15,Math.min(945,x));y=Math.max(15,Math.min(585,y));cr=cr.filter(c=>{if(Math.hypot(c.x-x,c.y-y)<24){score++;return false}return true});dr.forEach(d=>{d.x+=d.vx;d.y+=d.vy;if(d.x<0||d.x>960)d.vx*=-1;if(d.y<0||d.y>600)d.vy*=-1;if(Math.hypot(d.x-x,d.y-y)<25)hit=1});draw();if(cr.length&&!hit)raf=requestAnimationFrame(loop);else{local('miner',score);ui(hit?`DRONE HIT • ${score} CRYSTALS • BEST ${local('miner')}`:`MINED IT ALL • ${score} • BEST ${local('miner')}`)}};const draw=()=>{fill();ctx.fillStyle='#55ddff';cr.forEach(c=>{ctx.beginPath();ctx.moveTo(c.x,c.y-8);ctx.lineTo(c.x+8,c.y);ctx.lineTo(c.x,c.y+12);ctx.lineTo(c.x-8,c.y);ctx.closePath();ctx.fill()});ctx.fillStyle='#ff7a9d';dr.forEach(d=>{ctx.beginPath();ctx.arc(d.x,d.y,10,0,7);ctx.fill()});ctx.fillStyle='#bdb6ff';ctx.beginPath();ctx.arc(x,y,14,0,7);ctx.fill();ui(`CRYSTALS ${score}/${score+cr.length}`)};loop();}

  function tap(){shell('Tap Frenzy','Click/tap the canvas as many times as possible before the timer ends.');let left=300,last=Date.now(),started=false;const tapFn=()=>{if(!started)started=true;if(left>0)score++};canvas.addEventListener('pointerdown',tapFn);cleanup=()=>{canvas.removeEventListener('pointerdown',tapFn)};const loop=()=>{left-=1;if(left<=0){local('tap',score);ui(`TIME! ${score} TAPS • BEST ${local('tap')}`);return}draw();raf=requestAnimationFrame(loop)};const draw=()=>{fill();ctx.font='900 92px Space Grotesk, sans-serif';ctx.textAlign='center';ctx.fillText(String(score),480,280);ctx.font='700 20px Space Grotesk, sans-serif';ctx.fillText(`${Math.ceil(left/60)}s`,480,335);ctx.font='16px Space Grotesk, sans-serif';ctx.fillStyle='#8593ab';ctx.fillText(started?'KEEP GOING!':'CLICK / TAP ANYWHERE',480,380);ctx.textAlign='start'};loop();}

  function aim(){shell('Aim Rush','Click the target. 20 targets. Faster hits = higher score.');let left=20,target={x:480,y:300,r:30},start=Date.now();const newT=()=>{target={x:rand(50,910),y:rand(60,540),r:Math.max(12,30-score/4)}};newT();const hit=e=>{const r=canvas.getBoundingClientRect(),x=(e.clientX-r.left)/r.width*canvas.width,y=(e.clientY-r.top)/r.height*canvas.height;if(Math.hypot(x-target.x,y-target.y)<target.r){score+=Math.max(1,Math.floor(30-Math.min(24,(Date.now()-start)/100)));left--;start=Date.now();newT();if(!left){local('aim',score);ui(`DONE • ${score} • BEST ${local('aim')}`)}}};canvas.addEventListener('pointerdown',hit);cleanup=()=>canvas.removeEventListener('pointerdown',hit);const loop=()=>{draw();if(left)raf=requestAnimationFrame(loop)};const draw=()=>{fill();ctx.fillStyle='#6f65ff';ctx.beginPath();ctx.arc(target.x,target.y,target.r,0,7);ctx.fill();ctx.strokeStyle='#fff';ctx.beginPath();ctx.arc(target.x,target.y,target.r+8,0,7);ctx.stroke();ui(`TARGETS ${20-left}/20 • SCORE ${score}`)};loop();}

  function color(){shell('Color Switch','Choose the INK color of each word. 25 rounds.');const cols=['RED','BLUE','GREEN','YELLOW'],hex=['#ff6b7e','#6d7bff','#73e1a4','#ffd76d'];let round=0,current=0,ink=0;let btns=[];const make=()=>{current=int(0,3);ink=int(0,3);const b=$('#nxaStat');b.innerHTML='';for(let i=0;i<4;i++){const x=document.createElement('button');x.className='nxa-btn ghost';x.textContent=cols[i];x.onclick=()=>pick(i);b.parentElement.insertBefore(x,canvas);btns.push(x)}};const pick=i=>{if(i===ink)score+=2;else score--;round++;if(round>=25){local('color',score);ui(`DONE • ${score} • BEST ${local('color')}`);btns.forEach(x=>x.remove());return;}current=int(0,3);ink=int(0,3);draw()};const draw=()=>{fill();btns.forEach(x=>x.remove());btns=[];ctx.textAlign='center';ctx.font='900 70px Space Grotesk';ctx.fillStyle=hex[ink];ctx.fillText(cols[current],480,250);ctx.font='18px Space Grotesk';ctx.fillStyle='#8896ad';ctx.fillText('CLICK THE COLOR THAT THE INK IS',480,310);ctx.textAlign='start';make();ui(`ROUND ${round+1}/25 • SCORE ${score}`)};make();draw();}

  function math(){shell('Math Sprint','Click the correct answer. 45 seconds.');let left=270,a=0,b=0,op='+';const make=()=>{a=int(2,30);b=int(2,30);op=['+','−','×'][int(0,2)];};const val=()=>op==='+'?a+b:op==='−'?a-b:a*b;const click=e=>{const t=e.target;if(!t.matches('[data-answer]'))return;if(+t.dataset.answer===val())score+=2;else score--;make();render()};$('#nxaBody').addEventListener('click',click);cleanup=()=>$('#nxaBody').removeEventListener('click',click);const render=()=>{const ans=val(),set=new Set([ans]);while(set.size<4)set.add(ans+int(-12,12));const vals=[...set].sort(()=>Math.random()-.5);$('#nxaStat').innerHTML=`${a} ${op} ${b} = ?`;vals.forEach(v=>{const btn=document.createElement('button');btn.className='nxa-btn ghost';btn.dataset.answer=v;btn.textContent=v;$('#nxaStat').appendChild(btn)});ui(`TIME ${Math.ceil(left/60)}s • SCORE ${score}`)};make();render();const loop=()=>{left--;ui(`TIME ${Math.ceil(left/60)}s • SCORE ${score}`);if(left<=0){local('math',score);ui(`DONE • ${score} • BEST ${local('math')}`);return}raf=requestAnimationFrame(loop)};loop();}

  function lights(){shell('Memory Lights','Watch the sequence, then click the same buttons.');const colors=['#7b6cff','#54d8ff','#73e1a4','#ffd76d'];let seq=[],user=[],step=0,locked=true,round=1,buttons=[];const build=()=>{const wrap=document.createElement('div');wrap.className='nxa-controls';for(let i=0;i<4;i++){const b=document.createElement('button');b.className='nxa-btn ghost';b.style.width='110px';b.style.height='70px';b.dataset.i=i;b.onclick=()=>pick(i);wrap.appendChild(b);buttons.push(b)}canvas.replaceWith(wrap);canvas=null;};const flash=async()=>{locked=true;for(const n of seq){buttons[n].style.background=colors[n];await new Promise(r=>setTimeout(r,280));buttons[n].style.background='';await new Promise(r=>setTimeout(r,120))}locked=false};const pick=i=>{if(locked)return;user.push(i);if(i!==seq[user.length-1]){local('lights',score);ui(`BUSTED • ROUND ${round} • BEST ${local('lights')}`);locked=true;return}if(user.length===seq.length){score+=round;round++;user=[];seq.push(int(0,3));ui(`NICE • ROUND ${round}`);flash()}};build();seq=[int(0,3),int(0,3)];flash();}

  function tiles(){shell('Tile Rush','Click adjacent pairs to merge. A compact 2048-style original.');let cells=Array(25).fill(0);cells[int(0,24)]=2;cells[int(0,24)]=2;const b=document.createElement('div');b.className='nxa-controls';b.style.maxWidth='440px';b.style.display='grid';b.style.gridTemplateColumns='repeat(5,1fr)';b.style.width='100%';$('#nxaBody').querySelector('.nxa-board').insertBefore(b,$('#nxaBody').querySelector('.nxa-controls'));const draw=()=>{b.innerHTML=cells.map((v,i)=>`<button class="nxa-btn ${v?'':'ghost'}" data-i="${i}" style="min-height:58px;font-size:18px">${v||'·'}</button>`).join('');ui(`TILES • SCORE ${score}`);b.querySelectorAll('button').forEach(x=>x.onclick=()=>merge(+x.dataset.i))};const merge=i=>{const x=cells[i];if(!x)return;const n=[i-1,i+1,i-5,i+5].filter(j=>j>=0&&j<25&&Math.abs((j%5)-(i%5))+Math.abs(Math.floor(j/5)-Math.floor(i/5))===1).find(j=>cells[j]===x);if(n!=null){cells[n]=x*2;cells[i]=0;score+=x*2;local('tiles',score);draw()}};draw()}

  function maze(){shell('Maze Escape','Arrow keys / WASD. Reach the green exit.');const n=14,s=canvas.width/n;let p=[0,0],exit=[13,13],walls=[];for(let y=0;y<n;y++)for(let x=0;x<n;x++){if(Math.random()<.19&&!(x===0&&y===0)&&!(x===13&&y===13))walls.push(x+','+y)}let t=0;const loop=()=>{t++;draw();raf=requestAnimationFrame(loop)};const move=e=>{let q=[...p];if(['ArrowUp','w'].includes(e.key))q[1]--;if(['ArrowDown','s'].includes(e.key))q[1]++;if(['ArrowLeft','a'].includes(e.key))q[0]--;if(['ArrowRight','d'].includes(e.key))q[0]++;if(q[0]>=0&&q[0]<n&&q[1]>=0&&q[1]<n&&!walls.includes(q.join(',')))p=q;if(q[0]===exit[0]&&q[1]===exit[1]){score=Math.max(1,300-Math.floor(t/3));local('maze',score);ui(`ESCAPED • ${score} • BEST ${local('maze')}`);window.removeEventListener('keydown',move)}};window.addEventListener('keydown',move);cleanup=()=>window.removeEventListener('keydown',move);const draw=()=>{fill();for(let y=0;y<n;y++)for(let x=0;x<n;x++){ctx.fillStyle=walls.includes(x+','+y)?'#1b2940':'#08101a';ctx.fillRect(x*s,y*s,s-2,s-2)}ctx.fillStyle='#73e1a4';ctx.fillRect(exit[0]*s+8,exit[1]*s+8,s-16,s-16);ctx.fillStyle='#7b6cff';ctx.fillRect(p[0]*s+8,p[1]*s+8,s-16,s-16);ui(`TIME ${Math.floor(t/60)}s`)};loop()}

  function rhythm(){shell('Beat Tap','Click when the moving marker is inside the center ring.');let x=0,v=9,left=30;const hit=e=>{const r=canvas.getBoundingClientRect(),mx=(e.clientX-r.left)/r.width*canvas.width;const d=Math.abs(mx-480);if(d<65)score+=3;else if(d<130)score+=1;else score--;left--;};canvas.addEventListener('pointerdown',hit);cleanup=()=>canvas.removeEventListener('pointerdown',hit);const loop=()=>{x+=v;if(x>920||x<40)v*=-1;draw();if(left>0)raf=requestAnimationFrame(loop);else{local('rhythm',score);ui(`DONE • ${score} • BEST ${local('rhythm')}`)}};const draw=()=>{fill();ctx.fillStyle='#6f65ff';ctx.fillRect(40,285,880,30);ctx.fillStyle='#fff';ctx.beginPath();ctx.arc(480,300,62,0,7);ctx.stroke();ctx.fillStyle='#73e1a4';ctx.fillRect(445,278,70,44);ctx.fillStyle='#ff7a9d';ctx.beginPath();ctx.arc(x,300,18,0,7);ctx.fill();ui(`HITS ${30-left}/30 • SCORE ${score}`)};loop()}

  function orbit(){shell('Orbit Dodger','Arrow keys. Rotate around the core; avoid incoming dots.');const k=keySet();let a=0,rad=170,obs=[],t=0,dead=0;for(let i=0;i<22;i++)obs.push({a:rand(0,6.28),r:rand(40,420),v:rand(1.2,3.5)});const loop=()=>{a+=(k.has('a')||k.has('arrowleft')?-0.05:0)+(k.has('d')||k.has('arrowright')?0.05:0);t++;obs.forEach(o=>{o.r-=o.v;if(o.r<40){o.r=420;o.a=rand(0,6.28);score++}const px=480+Math.cos(a)*rad,py=300+Math.sin(a)*rad,ox=480+Math.cos(o.a)*o.r,oy=300+Math.sin(o.a)*o.r;if(Math.hypot(px-ox,py-oy)<18)dead=1});draw();if(t<3600&&!dead)raf=requestAnimationFrame(loop);else{local('orbit',score);ui(dead?`HIT • ${score} • BEST ${local('orbit')}`:`SURVIVED • ${score} • BEST ${local('orbit')}`)}};const draw=()=>{fill();ctx.strokeStyle='#27354a';ctx.beginPath();ctx.arc(480,300,rad,0,7);ctx.stroke();ctx.fillStyle='#ffd76d';ctx.beginPath();ctx.arc(480,300,28,0,7);ctx.fill();obs.forEach(o=>{ctx.fillStyle='#ff6b7e';ctx.beginPath();ctx.arc(480+Math.cos(o.a)*o.r,300+Math.sin(o.a)*o.r,5,0,7);ctx.fill()});ctx.fillStyle='#7b6cff';ctx.beginPath();ctx.arc(480+Math.cos(a)*rad,300+Math.sin(a)*rad,12,0,7);ctx.fill();ui(`SCORE ${score} • TIME ${(t/60).toFixed(1)}s`)};loop()}

  function scramble(){shell('Word Scramble','Type the original word. 30 seconds.');let left=180,word='',scr='';const input=document.createElement('input');input.className='nxa-search';input.placeholder='Unscramble it…';$('#nxaBody').querySelector('.nxa-board').insertBefore(input,$('#nxaBody').querySelector('.nxa-controls'));const next=()=>{word=words[int(0,words.length-1)];scr=word.split('').sort(()=>Math.random()-.5).join('');ui(`${scr} • SCORE ${score}`);input.value='';input.focus()};input.addEventListener('keydown',e=>{if(e.key==='Enter'){if(input.value.trim().toUpperCase()===word)score+=3;else score--;next()}});cleanup=()=>input.remove();next();const loop=()=>{left--;ui(`${scr} • TIME ${Math.ceil(left/60)}s • SCORE ${score}`);if(left<=0){local('scramble',score);ui(`DONE • ${score} • BEST ${local('scramble')}`);return}raf=requestAnimationFrame(loop)};loop()}

  function clicker(){shell('Cosmic Clicker','Click the core. Buy simple multipliers with your streak.');let mult=1,left=900;canvas.addEventListener('pointerdown',()=>{score+=mult});const buy=document.createElement('button');buy.className='nxa-btn';buy.textContent='Buy +1 multiplier (50)';buy.onclick=()=>{if(score>=50){score-=50;mult++}};$('#nxaBody').querySelector('.nxa-board').appendChild(buy);cleanup=()=>buy.remove();const loop=()=>{left--;fill();ctx.fillStyle='#7b6cff';ctx.beginPath();ctx.arc(480,300,120+Math.sin(frame++/8)*8,0,7);ctx.fill();ctx.fillStyle='#fff';ctx.beginPath();ctx.arc(480,300,82,0,7);ctx.fill();ctx.fillStyle='#111827';ctx.font='900 38px Space Grotesk';ctx.textAlign='center';ctx.fillText('CLICK',480,315);ctx.textAlign='start';ui(`SCORE ${score} • x${mult} • ${Math.ceil(left/60)}s`);if(left>0)raf=requestAnimationFrame(loop);else{local('clicker',score);ui(`DONE • ${score} • BEST ${local('clicker')}`)}};loop()}

  function openWeb(url,title){open();const b=$('#nxaBody');b.innerHTML=`<div class="nxa-web"><div class="nxa-webcard"><h3>${esc(title)}</h3><p>This game source is hosted on the web and is opened in its own tab so NEXUS does not copy or redistribute third-party code or assets.</p><button class="nxa-btn" id="nxaOpenWeb">Open game ↗</button><button class="nxa-btn ghost" id="nxaBackWeb">Arcade</button></div><div class="nxa-webcard"><h3>Why it is here</h3><p>These are curated web-game projects with public/open-source repositories. Always keep the original project and license notices with any code you choose to reuse.</p><button class="nxa-btn ghost" id="nxaSource">View source ↗</button></div></div>`;$('#nxaOpenWeb').onclick=()=>window.open(url,'_blank','noopener,noreferrer');$('#nxaBackWeb').onclick=home;$('#nxaSource').onclick=()=>window.open(url,'_blank','noopener,noreferrer');}

  function mount(){
    const nav=document.querySelector('.nav-group'); if(nav&&!document.getElementById('nexaArcadeBtn')){const btn=document.createElement('button');btn.className='nav-item';btn.id='nexaArcadeBtn';btn.innerHTML='🎮 <span>Arcade</span><b style="margin-left:auto;color:#7c6cff;font-size:9px">NEW</b>';btn.onclick=renderHome;nav.appendChild(btn)}
    if(!window.NEXUS_ARCADE){window.NEXUS_ARCADE={open:renderHome,random:()=>launch(games[int(0,games.length-1)][0])};}
  }
  if(document.readyState==='loading')document.addEventListener('DOMContentLoaded',mount);else mount();
  return {open:renderHome};
})();
